### ISSUE TITLE
Update BTCPay

### ISSUE THREAD

**Issue by MaxHillebrand** [debian-cryptoanarchy/cryptoanarchy-deb-repo-builder#169]
BTCPay just released [v1.2.0](https://github.com/btcpayserver/btcpayserver/releases/tag/v1.2.0), a major release, would be nice to be up to date with it soon.

**Comment by Kixunil** [comment]
It's marked as pre-release so I'd wait with it for full release unless there's something very important (I don't see anything).

**Comment by Kixunil** [comment]
1.2.1 is now in experimental.

**Comment by MaxHillebrand** [comment]
tACK experimental

**Comment by Kixunil** [comment]
We should also upgrade nbxplorer to get this fix in: https://github.com/dgarage/NBXplorer/pull/324

While it may be nicer to add recommends `nbxplorer-{variant} (>= 2.1.58)` to `btcpayserver-system-@variant`, I think it's not worth rebuilding the package as most people will do simple upgrade anyway and this bug is mostly related to testing. (I doubt any mining pool uses BTCPay hot wallet in our repo to mine :))

**Comment by Kixunil** [comment]
Done.
