### ISSUE TITLE
Current state and general questions

### ISSUE THREAD

**Issue by ossii79** [debian-cryptoanarchy/cryptoanarchy-deb-repo-builder#191]
Been wanting to move away from umbrel and these finished platforms to have a node running what I need and exactly that.
Having everything installed and updated via apt sure is tempting.

However some questions came to mind
- I see on github that there is a commit about two weeks ago that gives lnd 0.14.1, however just as a test I added the repo and did a apt-search which gives me "lnd/beta 0.13.3-1 amd64". Do I have to build and selfhost the repo to stay 100% updated?
- "Do **not** attempt to configure anything - it will just work" is stated twice, but there are tweaks I may want to implement to config files, minchansize, basefee/ppm for new channels, routerrpc tweaks to lnd.conf etc. Will such settings be overwritten with default values?
Or are we able to add just the tweaks below conf.d/my_routerrpc_tweaks.conf for example?

**Comment by Kixunil** [comment]
Happy to see another person interested!

Regarding commits, `master` branch currently reflects what's in `experimental` repository, not `beta`. I've been thinking about changing it as a part of #173. The reason things go through experimental is to catch bugs and avoid breaking peoples systems even if it means lagging behind a little. (Urgent fixes, especially security, stay in experimental for much shorter - sometimes just a few minutes.) This already proved useful since it caught one quite nasty issue and had impact on one instance only. Latest LND specifically brings significant changes not only to the daemon itself but to the packaging so that the newest featurescan be used. Thus I'm much more careful with this release. That being said, so far it seemed to work well and I expect to move it to `beta` in early January.

> Will such settings be overwritten with default values?

Depends on which settings. In general I tried to make it as nicely configurable as possible without affecting the interaction between packages. So yes, most of the times you can put stuff in `conf.d/...` and then run `dpkg-reconfigure` to re-generate the config and it'll work and stay configured during updates. However if available you must use debconf instead because it syncs the changes with other apps where relevant (ports, paths...) and makes it easier to handle configuration migrations. (One of the reasons latest LND took so long to upgrade was because I didn't put `tor.active` in debconf from beginning and I knew people overrode it manually and had to account for that. I'm thinking of adding everything into debconf to avoid such situations in the future.)

Note that even in case of migrations I strive to preserve the meaning of configuration. E.g. when upgrading LND from pre-0.11 a hostname entered in externalip is moved to externalhosts.

There are some configuration options that currently can not be safely changed, mainly ports and paths on the client side and some system paths (things in `/var/run` etc). This hopefully shouldn't be required but if you have a specific use case that needs it we can discuss how to solve it cleanly.

**Comment by ossii79** [comment]
Thanks for a very good reply, not often you see these lengthy ones from project maintainers ;)

In regards to the settings, still learning about running nodes, how to optimize both processing and profitability wise.
Came across settings like these: https://plebnet.wiki/wiki/Special:MyLanguage/LND_Configuration_Settings
Probably others that pop up as time passes. Though talking about tweaks, not ports and paths.

Keep up the good work! :)

**Comment by Kixunil** [comment]
From the options you linked only `alias` is currently in debconf.
I also noticed they mention sections but those are not mandatory and I recommend against them because they are not handled by deb packages and could lead to confusing configuration files.

Tor will be slightly involved in the upcoming version. If it's already running during LND installation and `DEBIAN_PRIORITY` is `medium` or `low` you will be asked if you want it on (default yes) and if you want it mixed (default yes), so the node will connect to onion nodes via onion and to clearnet nodes via clearnet. This is more reliable but less private. You can change the settings but note that currently there's no guarantee that LND will not be reachable via clearnet.
If you have higher `DEBIAN_PRIORITY` you will not be asked and the defaults will be used.
If Tor is *not* running you will **not** be asked regardless of `DEBIAN_PRIORITY` and it will **not** use Tor at all.

Electrum is unrelated to LND and currently some nice bridging is **not** implemented. I personally tunnel it over SSH but also know someone who uses Tor - it's actually pretty easy to setup.

**Comment by ossii79** [comment]
Great, thanks for answers. I'll give it a go and see if I can get things running as I want it.
